/**
 * Applets — gallery of saved LLM-generated custom UIs.
 */
'use client';

import { Code, Layout, Plus } from 'lucide-react';
import Link from 'next/link';

const EXAMPLE_APPLETS = [
	{
		id: 'example-1',
		title: 'Reading List',
		description: 'Saved URLs displayed as a reading list with status tracking.',
		updatedAt: '2 hours ago',
	},
	{
		id: 'example-2',
		title: 'Project Kanban',
		description: 'Project entities organized as a Kanban board.',
		updatedAt: '1 day ago',
	},
	{
		id: 'example-3',
		title: 'Topic Clusters',
		description: 'Visual clusters of related documents by topic.',
		updatedAt: '3 days ago',
	},
];

export default function AppletsPage() {
	return (
		<div>
			<div className="page-header-row">
				<h2 style={{ fontSize: '1.5rem', fontWeight: 600 }}>Applets</h2>
				<Link
					href="/applets/new"
					style={{
						display: 'flex',
						alignItems: 'center',
						gap: '0.375rem',
						padding: '0.5rem 1rem',
						backgroundColor: 'var(--text-accent)',
						color: '#000',
						border: 'none',
						borderRadius: '0.5rem',
						fontWeight: 600,
						fontSize: '0.8125rem',
						textDecoration: 'none',
						cursor: 'pointer',
					}}
				>
					<Plus size={16} />
					New Applet
				</Link>
			</div>

			<p style={{ color: 'var(--text-muted)', fontSize: '0.875rem', marginBottom: '1.5rem' }}>
				Custom interfaces generated by AI for your data. Each applet runs in a secure sandbox.
			</p>

			<div
				style={{
					display: 'grid',
					gridTemplateColumns: 'repeat(auto-fill, minmax(var(--grid-min-card), 1fr))',
					gap: '1rem',
				}}
			>
				{/* Create new card */}
				<Link
					href="/applets/new"
					style={{
						display: 'flex',
						flexDirection: 'column',
						alignItems: 'center',
						justifyContent: 'center',
						gap: '0.75rem',
						padding: '2rem',
						border: '2px dashed var(--border-default)',
						borderRadius: '0.75rem',
						cursor: 'pointer',
						textDecoration: 'none',
						color: 'var(--text-muted)',
						minHeight: 160,
					}}
				>
					<Plus size={24} />
					<span style={{ fontSize: '0.875rem', fontWeight: 500 }}>Create with AI</span>
				</Link>

				{/* Example applet cards */}
				{EXAMPLE_APPLETS.map((applet) => (
					<Link
						key={applet.id}
						href={`/applets/${applet.id}`}
						style={{
							display: 'flex',
							flexDirection: 'column',
							padding: '1.25rem',
							backgroundColor: 'var(--bg-secondary)',
							border: '1px solid var(--border-default)',
							borderRadius: '0.75rem',
							textDecoration: 'none',
							color: 'inherit',
							minHeight: 160,
						}}
					>
						<div
							style={{
								display: 'flex',
								alignItems: 'center',
								gap: '0.5rem',
								marginBottom: '0.75rem',
							}}
						>
							<Layout size={16} style={{ color: 'var(--text-accent)' }} />
							<span style={{ fontWeight: 600, fontSize: '0.9375rem' }}>{applet.title}</span>
						</div>
						<p style={{ color: 'var(--text-muted)', fontSize: '0.8125rem', flex: 1 }}>
							{applet.description}
						</p>
						<div
							style={{
								display: 'flex',
								alignItems: 'center',
								justifyContent: 'space-between',
								marginTop: '1rem',
							}}
						>
							<span style={{ fontSize: '0.6875rem', color: 'var(--text-muted)' }}>
								Updated {applet.updatedAt}
							</span>
							<Code size={14} style={{ color: 'var(--text-muted)' }} />
						</div>
					</Link>
				))}
			</div>
		</div>
	);
}
